version: "3.6"
services:
    ctcache:
        build: .
        environment:
            CTCACHE_PORT: 5001
        ports:
            - "5001:5001"
        volumes:
            - "ctcache:/var/lib/ctcache"
volumes:
    ctcache:
